version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reviewdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/schemes.sql:/docker-entrypoint-initdb.d/01-schemes.sql
    restart: unless-stopped

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=reviewdb
      - DB_SSL_MODE=disable
      - MODEL_URL=http://model:8081/predict
    restart: unless-stopped

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped

  frontend:
    build:
      context: ./sentiment-dashboard
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://hackathon.gberdyshev.org:8080
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data: 
