// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/predict": {
            "post": {
                "description": "Принимает список комментариев и возвращает предсказанные темы и тональности для каждого",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prediction"
                ],
                "summary": "Анализ комментариев",
                "parameters": [
                    {
                        "description": "Комментарии для анализа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PredictionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PredictionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/statistics": {
            "get": {
                "description": "Возвращает статистику за весь период.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Получение статистики",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatisticResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервиса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Comment": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "text": {
                    "type": "string",
                    "example": "Очень понравилось обслуживание в отделении, но мобильное приложение часто зависает."
                }
            }
        },
        "models.Prediction": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "sentiments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['положительно'",
                        " 'отрицательно']"
                    ]
                },
                "topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['Обслуживание'",
                        " 'Мобильное приложение']"
                    ]
                }
            }
        },
        "models.PredictionRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Comment"
                    }
                }
            }
        },
        "models.PredictionResponse": {
            "type": "object",
            "properties": {
                "predictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Prediction"
                    }
                }
            }
        },
        "models.Product": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "ипотека"
                },
                "timeline": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TimePoint"
                    }
                }
            }
        },
        "models.StatisticResponse": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Product"
                    }
                }
            }
        },
        "models.TimePoint": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "01.01.2024"
                },
                "negative": {
                    "type": "integer",
                    "example": 100
                },
                "neutral": {
                    "type": "integer",
                    "example": 10
                },
                "positive": {
                    "type": "integer",
                    "example": 50
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API",
	Description:      "Server for LCT hackathon",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
