basePath: /
definitions:
  models.Comment:
    properties:
      id:
        example: 1
        type: integer
      text:
        example: Очень понравилось обслуживание в отделении, но мобильное приложение
          часто зависает.
        type: string
    type: object
  models.Prediction:
    properties:
      id:
        example: 1
        type: integer
      sentiments:
        example:
        - '[''положительно'''
        - ' ''отрицательно'']'
        items:
          type: string
        type: array
      topics:
        example:
        - '[''Обслуживание'''
        - ' ''Мобильное приложение'']'
        items:
          type: string
        type: array
    type: object
  models.PredictionRequest:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Comment'
        type: array
    type: object
  models.PredictionResponse:
    properties:
      predictions:
        items:
          $ref: '#/definitions/models.Prediction'
        type: array
    type: object
  models.Product:
    properties:
      name:
        example: ипотека
        type: string
      timeline:
        items:
          $ref: '#/definitions/models.TimePoint'
        type: array
    type: object
  models.StatisticResponse:
    properties:
      products:
        items:
          $ref: '#/definitions/models.Product'
        type: array
    type: object
  models.TimePoint:
    properties:
      date:
        example: 01.01.2024
        type: string
      negative:
        example: 100
        type: integer
      neutral:
        example: 10
        type: integer
      positive:
        example: 50
        type: integer
    type: object
host: hackathon.gberdyshev.org:8080
info:
  contact: {}
  description: Server for LCT hackathon
  title: API
  version: "1.0"
paths:
  /predict:
    post:
      consumes:
      - application/json
      description: Принимает список комментариев и возвращает предсказанные темы и
        тональности для каждого
      parameters:
      - description: Комментарии для анализа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.PredictionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PredictionResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Анализ комментариев
      tags:
      - prediction
  /statistics:
    get:
      consumes:
      - application/json
      description: Возвращает статистику за весь период.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StatisticResponse'
        "500":
          description: Внутренняя ошибка сервиса
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение статистики
      tags:
      - statistics
swagger: "2.0"
